styleguide: sourcelevel/linters
engines:
  eslint:
    enabled: true
  fixme:
    enabled: true
  remark-lint:
    enabled: true
exclude_paths:
  - docs
  - test
  - coverage
  - node_modules
  - .nyc_output
